### ISSUE TITLE
NPA button not disappearing

### ISSUE THREAD

**Issue by TheTechRobo** [owendaigle/trmWebsite#1]
because i have a SmallScreen

**Comment by owendaigle** [comment]
fixed the problem. Now all NPA members will need to be notified on the new way of accessing it.
The one issue, is that I think that now there is no longer mobile compatibility.

**Comment by TheTechRobo** [comment]
Maybe if they're on mobile you should modify it i.e. have another place for the button

**Comment by TheTechRobo** [comment]
Fixed; it now uses the improved code. We will still need to add mobile compatibility
