### ISSUE TITLE
this does not look right

### ISSUE THREAD

**Issue by TheTechRobo** [owendaigle/trmWebsite#10]
![image](https://user-images.githubusercontent.com/52163910/102416495-ebada680-3fc7-11eb-8fa6-cbd9e3c7dc0e.png)

all that blank space where the logo used to be? i don't like that. move up the content a little bit.

**Comment by owendaigle** [comment]
Ill do that in the next patch

**Comment by TheTechRobo** [comment]
Sounds good.

**Comment by owendaigle** [comment]
done in the beta branch
