### ISSUE TITLE
icon

### ISSUE THREAD

**Issue by TheTechRobo** [owendaigle/trmWebsite#12]
![image](https://user-images.githubusercontent.com/52163910/102416621-2adbf780-3fc8-11eb-959c-2023a127bcc8.png)

also:

![image](https://user-images.githubusercontent.com/52163910/102416772-77273780-3fc8-11eb-9579-3f8b19e49a94.png)

IMO a website favicon should either have no background, or be rounded. It blends in more, like so:

![image](https://user-images.githubusercontent.com/52163910/102416714-58c13c00-3fc8-11eb-8ab8-f4829c77cb54.png)

**Comment by owendaigle** [comment]
I agree, I am just too lazy to change them. I might do that sometime in the future though.

**Comment by TheTechRobo** [comment]
Sounds good.

**Comment by owendaigle** [comment]
so I tried to change it, but none of the free online software seems to work. I think i'll have to install photoshop sometime to try to fix it.

**Comment by TheTechRobo** [comment]
try gimp

also, try searching up "freehand crop"

Not sure if it'd work but pixlr x is also a good online editor

**Comment by owendaigle** [comment]
thanks
![trmicon3circle](https://user-images.githubusercontent.com/52384666/103800218-2086a980-501a-11eb-8087-2fa207d54336.png)

**Comment by owendaigle** [comment]
it looks ok...
but not great

**Comment by owendaigle** [comment]
my photo editing skills are 
...
Bad

**Comment by TheTechRobo** [comment]
it looks ok

**Comment by owendaigle** [comment]
but the edges arent round. They are like a wall

**Comment by TheTechRobo** [comment]
oh yeah

**Comment by TheTechRobo** [comment]
![icon](https://i.ibb.co/mc76rcH/trmicon-circle.png)

https://crop-circle.imageonline.co/#circlecropresult

**Comment by owendaigle** [comment]
thats a great website, and that is a great icon. Thanks, ill add it in the next update

**Comment by owendaigle** [comment]
live

**Comment by owendaigle** [comment]
I meant live for the main icon

**Comment by TheTechRobo** [comment]
Yeah, that looks much better.

![image](https://user-images.githubusercontent.com/52163910/103954091-7ab66600-5111-11eb-8513-3ec97e65d6da.png)

**Comment by TheTechRobo** [comment]
Does this one look good for the MC logo?

![image](https://user-images.githubusercontent.com/52163910/103954687-c4538080-5112-11eb-972c-9b88cfad1226.png)

**Comment by owendaigle** [comment]
It does but I think that I have a better Mc icon where the block is less zoomed in

**Comment by TheTechRobo** [comment]
Sounds good.

**Comment by TheTechRobo** [comment]
@theruntingmuumuu ping

**Comment by owendaigle** [comment]
Finally done on beta 2.10
