### ISSUE TITLE
Everything should have the same theme IMO

### ISSUE THREAD

**Issue by TheTechRobo** [owendaigle/trmWebsite#13]
In my opinion, the minecraft site:

![image](https://user-images.githubusercontent.com/52163910/102417333-793dc600-3fc9-11eb-871f-885e94088fb2.png)

should look similar to if not the same as the ESO site:

![image](https://user-images.githubusercontent.com/52163910/102417366-878be200-3fc9-11eb-82df-2eff70771171.png)

**Comment by owendaigle** [comment]
The reason that I updated to beta 2, is because I want there to be different themes for different parts of the site. I want to treat them all as basically different sites, with the only common thing being that they are all hosted on the same server.

**Comment by owendaigle** [comment]
That is why I have the big menu at the start of the site with all the links to the other sections

**Comment by TheTechRobo** [comment]
Ah. Sounds good.
