### ISSUE TITLE
Update GitHub

### ISSUE THREAD

**Issue by TheTechRobo** [owendaigle/trmWebsite#15]
pleaee make sure to keep my new changelog files.

this is why github needs to sync. easier to make contributions.

**Comment by owendaigle** [comment]
well I may have accidentally deleted the new changelog (without knowing) but I did update the repos. You can update the changelog in the beta branch if you want

**Comment by owendaigle** [comment]
and I did not mean to click close

**Comment by TheTechRobo** [comment]
> and I did not mean to click close

Try the chrome extension Refined Github, it does many changes like moves the close button further away, like so (don't mind the ugliness, Old School GitHub (an extension) is conflicting with the new dark mode):

![image](https://user-images.githubusercontent.com/52163910/102695749-47aa4200-41f7-11eb-9f25-dc74070a471c.png)

**Comment by owendaigle** [comment]
so I think that this is done now, and FYI I have refined github and I like it a lot since I will not accidentally click **close with comment** instead of **comment**

**Comment by owendaigle** [comment]
and there I accidentally clicked **comment** instead of **close with comment** :rage:
