### ISSUE TITLE
MC Mobile menu not working on beta

### ISSUE THREAD

**Issue by owendaigle** [owendaigle/trmWebsite#16]
Somehow, on the beta github pages site, the mobile menu does not work.

**Comment by owendaigle** [comment]
actually, none of the menu renders for some reason...

**Comment by owendaigle** [comment]
so it seems to be that for some reason github pages is not rendering any of the menu code. :-( 

Does anyone know why?

**Comment by TheTechRobo** [comment]
If it's PHP, GitHub Pages doesn't do PHP.

**Comment by TheTechRobo** [comment]
hm, let me test

**Comment by TheTechRobo** [comment]
Found it - the console is your mate with stuff like this, use it!

![Transcript: "Mixed Content: The page at 'https://theruntingmuumuu.github.io/trmWebsite/minecraft/index.html' was loaded over HTTPS, but requested an insecure script 'http://ajax.googleapis.com/ajax/libs/jquery/1.8.2/jquery.min.js'. This request has been blocked; the content must be served over HTTPS."](https://user-images.githubusercontent.com/52163910/102696587-6dd2e080-41fd-11eb-8dce-b40c9aa5c731.png)

what this means is you need to change the HTTP in the jquery thingy, to HTTPS. THIS WILL DROP SUPPORT FOR BROWSERS THAT CANNOT DO SSL, SO BE CAREFUL! What I'd suggest is to load it twice - one with the http for older browsers, one with the https for new browsers with that security rule. That brings the best of both worlds, but may slow it down a bit for slow connections.

**Comment by owendaigle** [comment]
fixed thanks @TheTechRobo

**Comment by TheTechRobo** [comment]
Yep, it works :)
