### ISSUE TITLE
isn't it doctype html ?

### ISSUE THREAD

**Issue by TheTechRobo** [owendaigle/trmWebsite#19]
you write:

`<!DOCTYPE html5>`

isn't it 

`<!DOCTYPE html>`???

**Comment by owendaigle** [comment]
I added html 5 since for some reason, some of the code only works then. I can't remember what code, but I had a reason.

**Comment by TheTechRobo** [comment]
Hm, that's odd. I can't find a single source on the 'net that uses `<!DOCTYPE html5>`.
