### ISSUE TITLE
NPA in Beta links to Alpha version

### ISSUE THREAD

**Issue by TheTechRobo** [owendaigle/trmWebsite#2]
Title says it all.

Easily reproducible and fixable.

**Comment by TheTechRobo** [comment]
since the beta is now replacing the alpha, this may be fixed by accident lol. i'm still not sure tho. @TheRuntingMuumuu has it been fixed?

**Comment by owendaigle** [comment]
well I never really saw this issue, but now it is fixed since the beta is now the alpha

**Comment by TheTechRobo** [comment]
Ok, sounds good.
