### ISSUE TITLE
Mobile compatibility for eso

### ISSUE THREAD

**Issue by owendaigle** [owendaigle/trmWebsite#20]
The eso menubar should work better on mobile. If I add anymore itwms, it will overflow on mobile

(Sorry for typos, I'm on mobile)

**Comment by TheTechRobo** [comment]
Do you have any ideas on how it can be implemented?

**Comment by owendaigle** [comment]
I am thinking of something similar to the design on the alpha site, but I may change it to something different later.

**Comment by owendaigle** [comment]
done
