### ISSUE TITLE
Add Sitemap

### ISSUE THREAD

**Issue by TheTechRobo** [owendaigle/trmWebsite#23]
I have created a rudimentary sitemap layout.

![image](https://user-images.githubusercontent.com/52163910/103492380-84318c80-4df8-11eb-9eca-688876eec391.png)

We need to add some style sheet stuff, but not too complicated, what I suggest doing is not using anything that netsurf doesn't support - netsurf is a fairly common browser that has been written from scratch. Anything on "not started" should not be used.

http://www.netsurf-browser.org/documentation/progress.html#ImportantHTML

**Comment by owendaigle** [comment]
that sounds good

**Comment by owendaigle** [comment]
It should be done now

**Comment by TheTechRobo** [comment]
yep
