### ISSUE TITLE
Use image maps

### ISSUE THREAD

**Issue by TheTechRobo** [owendaigle/trmWebsite#24]
I think that it'd be a good idea to try out "image maps" for your designs.

Pros -

- Much easier when starting - just use a random online photo editor
- Simpler CSS so it'd support more browsers

Cons - 

- May use slightly more internet
- Will need a photo editor every time you update it

I think the pros outweigh the cons. Here is a good website considering I doubt that you'll want to enter coordinates manually. 

https://www.image-map.net/

**Comment by owendaigle** [comment]
like what would I need this for

**Comment by TheTechRobo** [comment]
Just a basic design, e.g.

![image](https://user-images.githubusercontent.com/52163910/103561783-061cc680-4e88-11eb-8fb8-78393ad51ff1.png)

in that case, the basic layout and design is stored in the image. but you can also use image maps to add buttons and stuff without any css.

**Comment by TheTechRobo** [comment]
It's how I created my "wiibsite", here it is if you want to see. https://thetechroboextra.github.io (try clicking stuff)

Basically, with image maps, you can click on specific parts of the image and they act like buttons.

**Comment by TheTechRobo** [comment]
Do you want this or should I close the issue?

**Comment by owendaigle** [comment]
I'll keep this in mind and Ill use them if a need arises. I think they are cool but I dont think I have a need for them at the moment.
