### ISSUE TITLE
this is a rather silly bug

### ISSUE THREAD

**Issue by TheTechRobo** [owendaigle/trmWebsite#27]
![image](https://user-images.githubusercontent.com/52163910/103599907-338f6180-4ed4-11eb-9652-b99a6a51bae3.png)

**Comment by owendaigle** [comment]
yes I know, I have not updated the worlds page yet, I will once I finish the MC page redisign thing (there are still some bugs that I want to fix)

**Comment by owendaigle** [comment]
done
