### ISSUE TITLE
ESO mobile menu icons

### ISSUE THREAD

**Issue by owendaigle** [owendaigle/trmWebsite#28]
For some reason, I made 2 eso buttons that do completely different things have the same icon.
![Screenshot_20210105-221547_Edge](https://user-images.githubusercontent.com/52384666/103725321-4e310b80-4fa4-11eb-964e-7933c15b024e.jpg)

**Comment by owendaigle** [comment]
And I should also increase the full-page top margin 
`.fullpage {
    margin-top: 50px;
}`
To
`.fullpage {
    margin-top: 55px;
}`
Or something like that.


And btw, this is kind of just a note to myself

**Comment by owendaigle** [comment]
done

**Comment by TheTechRobo** [comment]
> And btw, this is kind of just a note to myself

yeah, people do that all the time in issues. :)
