### ISSUE TITLE
get the world downloads up

### ISSUE THREAD

**Issue by TheTechRobo** [owendaigle/trmWebsite#29]
You'll have to, since I don't have access to the server files.

**Comment by owendaigle** [comment]
I know, first I need to implement the new server though

**Comment by TheTechRobo** [comment]
You haven't already?? I thought it was due on the 26th or 27th.

**Comment by owendaigle** [comment]
I was going to but I forgot...

_and maybe I was a bit lazy..._

**Comment by TheTechRobo** [comment]
> _and maybe I was a bit lazy..._

I can relate to that. 0.10 of my calculator could've taken two months, but I stretched it out and it took six months lol

**Comment by TheTechRobo** [comment]
Have you implemented the new server yet?

**Comment by TheTechRobo** [comment]
Do you have the files? If so you can upload them here and I'll put them in

**Comment by owendaigle** [comment]
I have the files, but the problem is that they are on the server computer, and I am too lazy to transfer them over. 

That being said, I will do it someday.

**Comment by owendaigle** [comment]
done

**Comment by TheTechRobo** [comment]
yay :D
