### ISSUE TITLE
Other branch

### ISSUE THREAD

**Issue by owendaigle** [owendaigle/trmWebsite#30]
I am thinking of redoing the branch system.

Master = What is live on trm.ddns.net
Beta1 = What is live on beta site
Beta2 (or something else) = what is actually the beta

This will allow me to have other branches that are just to test one feature (like NPA mobile compatability) and post it live on the website while keeping the main beta not having any things from other branches. 

EX to test NPA mobile compatability on my phone
1. Edit code on NPA branch
2. Merge with beta1
3. push
4. check it out on phone
5. make changes
6. repush
7. check it out on phone (complete)
8. merge (or clone???) beta2 into beta1

Sorry if it is a bit confusing im in a rush and I wanted to get my ideas out quickly

**Comment by TheTechRobo** [comment]
yeah, makes sense.

**Comment by TheTechRobo** [comment]
if you'd do that, https://theruntingmuumuu.github.io/trmWebsite/coding/index.html needs a link change for the BETA source code

**Comment by owendaigle** [comment]
I actually did this like a week ago, now there is

1. Beta1 --> The beta code
2. betaSiteLive --> The website
