### ISSUE TITLE
ESO Image Small on Mobile

### ISSUE THREAD

**Issue by owendaigle** [owendaigle/trmWebsite#31]
On mobile the ESO images are mega small. They still only take up 30% of the page like they do on desktop mode which is too small.

**Comment by owendaigle** [comment]
![image](https://user-images.githubusercontent.com/52384666/106051404-659c7980-60b6-11eb-87ea-c35e078e0744.png)

**Comment by TheTechRobo** [comment]
Should be able to fix that with something like `@media` in css?

**Comment by owendaigle** [comment]
yes I know, I just wrote this so that I remember it

**Comment by owendaigle** [comment]
it should just be an easy 
`width: 100%;`
under the `@media` element I already have for the mobile compatability

**Comment by owendaigle** [comment]
> yes I know, I just wrote this so that I remember it

right now, I was looking for a quick way to use 5 minutes, so I rememberd this :-)

**Comment by owendaigle** [comment]
should be fixed on the beta

**Comment by TheTechRobo** [comment]
yeah, seems to work
