### ISSUE TITLE
Contact Me needs BG fix

### ISSUE THREAD

**Issue by owendaigle** [owendaigle/trmWebsite#32]
On the index.html, the background is darkened. That is not the case for the contact me page where I have not added the parent div element to the main box.

![image](https://user-images.githubusercontent.com/52384666/106342625-b2778000-626f-11eb-804c-a00682049030.png) (bad)
vs
![image](https://user-images.githubusercontent.com/52384666/106342630-b7d4ca80-626f-11eb-91aa-9ce03fbc2456.png) (good)

**Comment by TheTechRobo** [comment]
I kind of like the contact me page bug better, but that's my opinion

**Comment by owendaigle** [comment]
well I fixed it and I like it like this
