### ISSUE TITLE
Interesting wording

### ISSUE THREAD

**Issue by TheTechRobo** [owendaigle/trmWebsite#33]
> (30sec boot after 12mo)

So do you keep it on at all times? 12 months is a long time to wait for it to boot up

**Comment by TheTechRobo** [comment]
Also, TheRuntingMuumuu uses arch btw :P

**Comment by owendaigle** [comment]
no, I meant the installation is 12mo old and it still boots up in 30 seconds

**Comment by owendaigle** [comment]
I know the wording is bad, I am not a very good writer

You can change it if you want
