### ISSUE TITLE
why did you remove all compatibility for old browsers

### ISSUE THREAD

**Issue by TheTechRobo** [owendaigle/trmWebsite#37]
owen why did you remove all compatibility for old browsers
1) removed noJS capability
2) removed HTTP-only browser support (old SSL)
3) probably others :/

**Comment by owendaigle** [comment]
There is still nojs since I migrated to the sitemap. I still need to change the `<noscript>` link  to link to the new menu.

Second, not all of my webpages had http compatability, and there was code that was otherwise useless, so I'm the future I plan to download a local copy of jquery.

**Comment by TheTechRobo** [comment]
yeah, I got confused since I needed to scroll.

I'll close this issue as invalid.
