### ISSUE TITLE
i tink you broke something

### ISSUE THREAD

**Issue by TheTechRobo** [owendaigle/trmWebsite#39]
the 404 PAGE THINGY on the Coding site is broken.

![image](https://user-images.githubusercontent.com/52163910/107677930-c5735280-6c68-11eb-9262-1c34fc61369d.png)

I have to select the text 2 see :

![image](https://user-images.githubusercontent.com/52163910/107677953-cad09d00-6c68-11eb-80d1-9ab5f7ea8004.png)

**Comment by owendaigle** [comment]
I know... it used to work, but now it is broken for some reason...

**Comment by owendaigle** [comment]
well, it seems to work for me...

**Comment by owendaigle** [comment]
![image](https://user-images.githubusercontent.com/52384666/107854903-2461d480-6ded-11eb-886a-904693681b9a.png)

**Comment by TheTechRobo** [comment]
I don't know how to reproduce it anymore, since the coding page is finished.

Closing.
