### ISSUE TITLE
no js menu looks...suboptimal

### ISSUE THREAD

**Issue by TheTechRobo** [owendaigle/trmWebsite#4]
at least provide some decent css... that looks very messy and its kind of hard to read

![image](https://user-images.githubusercontent.com/52163910/100693898-db58c300-335b-11eb-901e-19a78ba86fc2.png)

**Comment by owendaigle** [comment]
I know, I dont want to put much effort since most people will have javascript, but if you want you can make a better looking one (that still follows the general theme)

**Comment by TheTechRobo** [comment]
Ok, I might do it later.

**Comment by owendaigle** [comment]
Fyi I am working on a sitemap that will replace the nojs menu

**Comment by TheTechRobo** [comment]
Sounds good! A sitemap would be nice.

**Comment by TheTechRobo** [comment]
Closing due to the planned sitemap.
