### ISSUE TITLE
(low priority) if javascript is enabled, no js menu should redirect to the main (home) page

### ISSUE THREAD

**Issue by TheTechRobo** [owendaigle/trmWebsite#5]
so if i turn javascript on and reload, it'll trigger a javascript redirect, and will redirect to index.html

Idk if its worth the effort, just a very slight improvement that is very low priority

**Comment by owendaigle** [comment]
ill think about adding that in the next update

**Comment by TheTechRobo** [comment]
Ok

**Comment by TheTechRobo** [comment]
I don't think this should be added.

Many browsers have javascript support, so won't be triggered by a noscript, but not enough for the web page to display correctly. 

I will now close the issue.

**Comment by TheTechRobo** [comment]
And anyway, the sitemap won't need javascript and will be present as a link on the home page......right?
