### ISSUE TITLE
Where is the changelog?

### ISSUE THREAD

**Issue by TheTechRobo** [owendaigle/trmWebsite#6]
the beta update doesn't seem to have a clear link to it. if it should be in the general page, add it to the main menu (if you dont like it, fix it once the general page is done)

**Comment by TheTechRobo** [comment]
found it at http://trm.ddns.net/Changelog. but there needs to be a link.

**Comment by owendaigle** [comment]
I agree
it will be put on the general page (I think) once I make it

**Comment by owendaigle** [comment]
done in beta 2.4.1
