### ISSUE TITLE
mobile compatibility for npa

### ISSUE THREAD

**Issue by TheTechRobo** [owendaigle/trmWebsite#8]

**Comment by owendaigle** [comment]
Do you have any ideas of how I can implement this

**Comment by TheTechRobo** [comment]
@TheRuntingMuumuu press an invisible button 10 times???

**Comment by TheTechRobo** [comment]
is this finished?

**Comment by owendaigle** [comment]
no, I have more important priorities at the moment such as the coding page, the school page, and a bunch of bugfixes

**Comment by TheTechRobo** [comment]
I thought it was, you merged the pull request
